import { MapDef, PilotDef, SpiritDef, SpiritId, Terrain, TraitId, UnitDef, WeaponDef } from './types';

// ---------- Spirits (SRW "seishin") ----------

export const SPIRITS: Record<SpiritId, SpiritDef> = {
  focus: { id: 'focus', name: 'Focus', cost: 15, desc: 'Evade +30% until end of enemy phase' },
  strike: { id: 'strike', name: 'Strike', cost: 20, desc: 'Next attack always hits' },
  valor: { id: 'valor', name: 'Valor', cost: 40, desc: 'Next attack damage x1.5' },
  grit: { id: 'grit', name: 'Grit', cost: 15, desc: 'Armor +400 until end of enemy phase' },
  guard: { id: 'guard', name: 'Guard', cost: 20, desc: 'Incoming damage halved until end of enemy phase' },
  accel: { id: 'accel', name: 'Accel', cost: 10, desc: 'Move +3 this turn' },
  flash: { id: 'flash', name: 'Flash', cost: 25, desc: 'Auto-dodge the next enemy attack' },
  snipe: { id: 'snipe', name: 'Snipe', cost: 20, desc: 'Next attack range +2' },
  zeal: { id: 'zeal', name: 'Zeal', cost: 10, desc: 'Will +15 (self)' },
  rouse: { id: 'rouse', name: 'Rouse', cost: 25, desc: 'Will +10 to allies within 2 tiles' },
  disrupt: { id: 'disrupt', name: 'Disrupt', cost: 25, desc: 'Will -10 to enemies within 2 tiles' },
  bless: { id: 'bless', name: 'Bless', cost: 25, desc: 'Restore 40% HP (self)' },
  vigor: { id: 'vigor', name: 'Vigor', cost: 20, desc: 'Restore +40 EN (self)' },
  roar: { id: 'roar', name: 'Roar', cost: 15, desc: 'Will +20 (self)' },
  fortune: { id: 'fortune', name: 'Fortune', cost: 30, desc: 'Next attack grants double EXP' },
  soul: { id: 'soul', name: 'Soul', cost: 60, desc: 'Next attack damage x2' },
  trust: { id: 'trust', name: 'Trust', cost: 25, desc: 'Heal the most wounded ally within 2 tiles for 30% HP' },
  miracle: { id: 'miracle', name: 'Miracle', cost: 60, desc: 'Survive the next fatal hit with 10 HP — once' },
  vanish: { id: 'vanish', name: 'Vanish', cost: 40, desc: 'Enemies cannot target this unit until end of enemy phase' },
  lucky: { id: 'lucky', name: 'Lucky', cost: 45, desc: 'Next kill yields a guaranteed drop and +25cr salvage per enemy level' },
  overdrive: { id: 'overdrive', name: 'Overdrive', cost: 50, desc: 'Act again after landing a kill' },
  mercy: { id: 'mercy', name: 'Mercy', cost: 30, desc: 'Pull the next lethal hit — leave the foe at 10 HP for capture' },
  purge: { id: 'purge', name: 'Purge', cost: 40, desc: 'Cleanse self and adjacent allies — cripple, burn, stun, break lifted' },
  resolve: { id: 'resolve', name: 'Resolve', cost: 50, desc: 'Kiai surge — Will instantly climbs to 150' },
  sunder: { id: 'sunder', name: 'Sunder', cost: 45, desc: 'Breacher field — enemies within 3 tiles lose 300 armor & 15 evade' },
  provoke: { id: 'provoke', name: 'Provoke', cost: 35, desc: 'War horn — enemies within 3 tiles are drawn to attack this unit next phase' },
  cheer: { id: 'cheer', name: 'Cheer', cost: 30, desc: 'The most junior ally within 3 tiles gains double EXP on their next attack' },
  wish: { id: 'wish', name: 'Wish', cost: 50, desc: 'The most drained ally within 3 tiles regains +30 SP' },
  gravity: { id: 'gravity', name: 'Gravity Well', cost: 50, desc: 'Enemies within 3 tiles are anchored — they cannot move next phase' },
  guts: { id: 'guts', name: 'Guts', cost: 40, desc: 'Berserker surge — next attack deals +75% damage while under half HP' },
  expose: { id: 'expose', name: 'Expose', cost: 35, desc: 'Paint enemies within 3 tiles — next hit on each lands +20 hit, +25% damage' },
  decoy: { id: 'decoy', name: 'Decoy', cost: 45, desc: 'Deploy a holoreplica beside you — hostiles waste their attacks on it until next phase' },
  hymn: { id: 'hymn', name: 'Hymn', cost: 50, desc: 'Squad anthem — every ally gains +15 hit & +15 evade until end of enemy phase' },
  emp: { id: 'emp', name: 'EMP Burst', cost: 40, desc: 'Electromagnetic burst — the nearest enemy within 4 tiles is stunned, skipping its next activation' },
  phalanx: { id: 'phalanx', name: 'Phalanx', cost: 50, desc: 'Lock formation — every ally gains +400 armor until end of enemy phase' },
  deadshot: { id: 'deadshot', name: 'Deadshot', cost: 45, desc: 'Paint the kill-shot — your next attack is a guaranteed critical' },
  frenzy: { id: 'frenzy', name: 'Frenzy', cost: 40, desc: 'Push the reactor — your weapons cost no EN for the rest of this turn' },
  breach: { id: 'breach', name: 'Breach', cost: 45, desc: 'Overload the cutter — your next attack ignores all enemy armor' },
  relentless: { id: 'relentless', name: 'Relentless', cost: 35, desc: 'Blood in the water — +25% damage to enemies below half HP until the enemy phase ends' },
  reboot: { id: 'reboot', name: 'Reboot', cost: 45, desc: 'Restart the core — purge your own debuffs and restore 25% HP' },
  sanctuary: { id: 'sanctuary', name: 'Sanctuary', cost: 55, desc: 'Litany of the Ark — allies within 2 tiles recover 20% HP' },
  awaken: { id: 'awaken', name: 'Awaken', cost: 70, desc: 'Second wind — the nearest spent ally within 3 tiles acts again' },
  charity: { id: 'charity', name: 'Charity', cost: 30, desc: 'Bleed 20% own hull — the weakest ally within 2 tiles mends 40% HP' },
  siphon: { id: 'siphon', name: 'Siphon', cost: 35, desc: 'Drain 15 Will from the nearest enemy within 3 tiles' },
  intimidate: { id: 'intimidate', name: 'Intimidate', cost: 40, desc: 'War cry — enemies within 3 tiles suffer -20 hit for 2 turns' },
  scan: { id: 'scan', name: 'Scan', cost: 30, desc: 'Sensor sweep — enemies within 5 tiles are painted (+20 hit, +25% dmg taken)' },
  empower: { id: 'empower', name: 'Empower', cost: 40, desc: 'War blessing — the strongest ally within 3 tiles gains +40% damage on their next attack' },
  marksman: { id: 'marksman', name: 'Deadeye Call', cost: 45, desc: 'Squad fire control — every ally gains +15 crit until end of enemy phase' },
  ward: { id: 'ward', name: 'Ward', cost: 45, desc: 'Aegis prayer — the weakest ally within 3 tiles survives their next fatal hit at 1 HP' },
  warsong: { id: 'warsong', name: 'Warsong', cost: 55, desc: 'Anthem of the Ark — every ally gains +10% damage until end of enemy phase' },
  execute: { id: 'execute', name: 'Execution', cost: 50, desc: 'Coup de grace — your next hit destroys any non-boss, non-elite foe at 20% HP or less' },
  shatter: { id: 'shatter', name: 'Shatter', cost: 45, desc: 'Armor breaker — your next hit treats enemy armor as 50% before damage' },
  glacial: { id: 'glacial', name: 'Glacial', cost: 40, desc: 'Cryo strike — your next landed hit also inflicts Slow on the target' },
  relay: { id: 'relay', name: 'Relay', cost: 35, desc: 'Reactor tether — the most-drained ally within 3 tiles gains +30 EN' },
  soulburn: { id: 'soulburn', name: 'Soulburn', cost: 50, desc: 'Burn your own hull — costs 10% HP; your next hit deals +50% damage' },
  fluster: { id: 'fluster', name: 'Fluster', cost: 40, desc: 'Rattle their aim — your next landed hit also suppresses the target (-20 hit)' },
  hunt: { id: 'hunt', name: 'Hunt', cost: 45, desc: 'Wounded prey — your next hit deals +30% damage to targets below half HP' },
  tracer: { id: 'tracer', name: 'Tracer', cost: 40, desc: 'Designate the target — your next landed hit also marks it (+25 hit, +15% dmg taken)' },
  strafe: { id: 'strafe', name: 'Strafe', cost: 45, desc: 'Air superiority — your next hit deals +35% damage to a ground-frame target' },
  inspire: { id: 'inspire', name: 'Inspire', cost: 35, desc: 'A rallying cry — every ally gains +8 Will' },
  pyre: { id: 'pyre', name: 'Pyre', cost: 40, desc: 'Incendiary load — your next landed hit ignites the target (burn, 2 turns)' },
  overrun: { id: 'overrun', name: 'Overrun', cost: 45, desc: 'Shock assault — your next attack cannot be countered' },
  exert: { id: 'exert', name: 'Exert', cost: 40, desc: 'Push the reactor — your next attack gains +20 hit and +15% damage (costs 10 EN)' },
  veil: { id: 'veil', name: 'Veil', cost: 45, desc: 'Sensor mist — allies within 3 tiles gain +20 evade until end of enemy phase' },
  cantata: { id: 'cantata', name: 'Cantata', cost: 40, desc: 'Chorus of resolve — allies within 3 tiles recover +10 SP' },
  warhorn: { id: 'warhorn', name: 'Warhorn', cost: 40, desc: 'Battle horn — allies within 3 tiles deal +10% counter damage until end of enemy phase' },
  skyfall: { id: 'skyfall', name: 'Skyfall', cost: 45, desc: 'Anti-air dive — your next hit deals +35% damage to an airborne frame' },
  avenger: { id: 'avenger', name: 'Avenger', cost: 45, desc: 'Vengeful stance — your next counter-attack deals +50% damage' },
  reaper: { id: 'reaper', name: 'Reaper', cost: 50, desc: 'Dirge of the fallen — your next hit deals +10% damage per squad frame destroyed this battle' },
  stalker: { id: 'stalker', name: 'Stalker', cost: 40, desc: 'Predator instinct — your next hit deals +30% damage to a target carrying any status effect' },
  interfere: { id: 'interfere', name: 'Interference', cost: 45, desc: 'ECM flood — enemies within 3 tiles cannot counter-attack until end of their next phase' },
  safeguard: { id: 'safeguard', name: 'Safeguard', cost: 40, desc: 'Defensive perimeter — allies within 3 tiles take -10% damage until end of enemy phase' },
  blade: { id: 'blade', name: 'Bladestorm', cost: 45, desc: 'Blade dance — your next melee hit deals +40% damage' },
  suppress: { id: 'suppress', name: 'Suppress Fire', cost: 45, desc: 'Covering barrage — enemies within 3 tiles deal -10% damage until end of enemy phase' },
  carnage: { id: 'carnage', name: 'Carnage', cost: 50, desc: 'Shockwave strike — your next hit splashes 30% damage to enemies adjacent to the target' },
  trueshot: { id: 'trueshot', name: 'True Shot', cost: 40, desc: 'Zero-deflection round — your next hit ignores Defend and Cover reductions' },
  dischord: { id: 'dischord', name: 'Dischord', cost: 45, desc: 'Cacophony wave — enemies within 3 tiles lose 15 evade until the end of the enemy phase' },
  absolution: { id: 'absolution', name: 'Absolution', cost: 45, desc: 'Cleansing hymn — allies within 3 tiles shed all debuffs and gain +15 hit until the end of the enemy phase' },
  judge: { id: 'judge', name: 'Judgement', cost: 50, desc: 'Executioner sight — your next hit deals +50% damage against boss and elite frames' },
  banner: { id: 'banner', name: 'Banner', cost: 55, desc: 'Rally standard — allies within 3 tiles gain +10 hit and +20% counter damage until the end of the enemy phase' },
  gorelust: { id: 'gorelust', name: 'Gorelust', cost: 40, desc: 'Blood siphon — your next hit restores your hull by 25% of the damage dealt' },
  armorrot: { id: 'armorrot', name: 'Armor Rot', cost: 50, desc: 'Corrosion cascade — enemies within 3 tiles are sundered (armor crumbling, -15 evade) for the rest of the battle' },
  winterverse: { id: 'winterverse', name: 'Winter Verse', cost: 45, desc: 'Frost choir — enemies within 3 tiles are slowed (-3 move, 2 turns)' },
  litany: { id: 'litany', name: 'Litany', cost: 55, desc: 'Mending chorus — allies within 3 tiles recover 15% hull and shed all debuffs' },
  rampage: { id: 'rampage', name: 'Rampage', cost: 45, desc: 'Killing momentum — your next hit deals +8% damage per kill this battle (cap +40%)' },
  drawfire: { id: 'drawfire', name: 'Drawfire', cost: 35, desc: 'Beacon stance — enemies prioritize this frame until the end of the enemy phase' },
  hemorrhage: { id: 'hemorrhage', name: 'Hemorrhage', cost: 50, desc: 'Rending strike — your next hit burns AND paints the target' },
  lockcascade: { id: 'lockcascade', name: 'Lock Cascade', cost: 50, desc: 'Sensor cascade — every enemy within 4 tiles is painted (takes +20 hit, +25% damage on the next hit)' },
  wardmist: { id: 'wardmist', name: 'Ward Mist', cost: 45, desc: 'Veil of the verse — allies within 3 tiles are immune to enemy status until the end of the enemy phase' },
  aegis: { id: 'aegis', name: 'Aegis Hymn', cost: 45, desc: 'Aegis hymn — allies within 3 tiles cannot be struck by critical hits until the end of the enemy phase' },
  voidedge: { id: 'voidedge', name: 'Void Edge', cost: 45, desc: 'Phase blade — your next hit ignores all weapon-kind resistance on the target' },
  standfirm: { id: 'standfirm', name: 'Stand Firm', cost: 35, desc: 'Last bastion — this frame refuses the next fatal hit this phase (left at 1 HP)' },
  plunderedge: { id: 'plunderedge', name: 'Plunder Edge', cost: 45, desc: 'Scavenger blade — your next hit strips salvage worth 8% of the damage dealt' },
  firelink: { id: 'firelink', name: 'Firelink', cost: 45, desc: 'Targeting uplink — allies within 3 tiles gain +1 weapon range until the end of the enemy phase' },
  dreadverse: { id: 'dreadverse', name: 'Dread Verse', cost: 45, desc: 'Chorus of ruin — enemies within 3 tiles lose 15 Will' },
  sanctumhymn: { id: 'sanctumhymn', name: 'Sanctum Hymn', cost: 50, desc: 'Aegis chorus — allies within 3 tiles gain +400 armor until the end of the enemy phase' },
  tempestedge: { id: 'tempestedge', name: 'Tempest Edge', cost: 45, desc: 'Gale strike — your next hit hurls the target 1 tile backward' },
  ironoath: { id: 'ironoath', name: 'Iron Oath', cost: 45, desc: 'Unbreakable vow — +600 armor and enemies prioritize this frame until the end of the enemy phase' },
  lacerate: { id: 'lacerate', name: 'Lacerate', cost: 40, desc: 'Rending blow — your next hit also cracks the target armor (break)' },
  staticchoir: { id: 'staticchoir', name: 'Static Choir', cost: 45, desc: 'Static verse — enemies within 4 tiles are suppressed (−20 hit)' },
  dirgemist: { id: 'dirgemist', name: 'Dirge Mist', cost: 45, desc: 'Mourning veil — allies within 3 tiles restore 10% hull on each kill until the end of the enemy phase' },
  miraclechorus: { id: 'miraclechorus', name: 'Miracle Chorus', cost: 50, desc: 'Hymn of preservation — allies within 3 tiles survive their next fatal hit at 1 HP until the end of the enemy phase' },
  hellfire: { id: 'hellfire', name: 'Hellfire', cost: 50, desc: 'Incendiary aria — the next landed hit ignites the target and every foe adjacent to it' },
  bulwarkaria: { id: 'bulwarkaria', name: 'Bulwark Aria', cost: 45, desc: 'Anchoring hymn — allies within 3 tiles cannot be knocked back until the end of the enemy phase' },
  thrillkill: { id: 'thrillkill', name: 'Thrill Kill', cost: 40, desc: 'Predator rush — your next hit grants +15 Will if it kills' },
  pinverse: { id: 'pinverse', name: 'Pin Verse', cost: 45, desc: 'Binding chorus — hits landed by allies within 3 tiles also slow the target until the end of the enemy phase' },
  tideverse: { id: 'tideverse', name: 'Tide Verse', cost: 50, desc: 'Surging refrain — allies within 3 tiles gain +1 movement until the end of the enemy phase' },
  gracehymn: { id: 'gracehymn', name: 'Grace Hymn', cost: 45, desc: 'Renewal chorus — allies within 3 tiles recover +5% hull per turn for 2 turns' },
  sunderstorm: { id: 'sunderstorm', name: 'Sunderstorm', cost: 50, desc: 'Crushing wave — the next landed hit cracks the armor of the target and every foe adjacent to it' },
  mirrorwall: { id: 'mirrorwall', name: 'Mirror Wall', cost: 50, desc: 'Reflective anthem — allies within 3 tiles bounce 10% of damage taken back to the attacker until the end of the enemy phase' },
  ravenous: { id: 'ravenous', name: 'Ravenous', cost: 45, desc: 'Blood hunt — the next landed hit restores hull equal to 15% of damage and siphons 15 EN from the target' },
  breachverse: { id: 'breachverse', name: 'Breach Verse', cost: 45, desc: 'Fire-control chorus — attacks by allies within 3 tiles pierce 25% of target armor until the end of the enemy phase' },
  tideebb: { id: 'tideebb', name: 'Tide Ebb', cost: 45, desc: 'Ebb of the deep — enemies within 3 tiles lose 1 movement until the end of the enemy phase' },
  renewalverse: { id: 'renewalverse', name: 'Renewal Verse', cost: 50, desc: 'Sustaining hymn — allies within 3 tiles regenerate +10 EN each turn for 2 turns' },
  quakeedge: { id: 'quakeedge', name: 'Quake Edge', cost: 45, desc: 'Seismic blade — the next landed hit slows the target and every foe adjacent to it' },
  valiantverse: { id: 'valiantverse', name: 'Valiant Verse', cost: 45, desc: 'Underdog anthem — allies within 3 tiles gain +12% damage while outnumbered until the end of the enemy phase' },
  rageverse: { id: 'rageverse', name: 'Rage Verse', cost: 40, desc: 'Berserker hymn — the next attack hits harder the lower this frame hull is (up to +40%)' },
  exposeverse: { id: 'exposeverse', name: 'Expose Verse', cost: 50, desc: 'Sensor reveal — enemies within 3 tiles are exposed (+20 hit taken, +25% damage) until struck' },
  darkverse: { id: 'darkverse', name: 'Dark Verse', cost: 45, desc: 'Reactor drain — enemies within 3 tiles lose 15 EN instantly' },
  foresightverse: { id: 'foresightverse', name: 'Foresight Verse', cost: 45, desc: 'Precognition hymn — allies within 3 tiles gain +20 evade for 2 turns' },
  heavensverse: { id: 'heavensverse', name: 'Heaven Verse', cost: 50, desc: 'Storm wrath — a landed hit stuns the target and every enemy adjacent to it' },
  bastionverse: { id: 'bastionverse', name: 'Bastion Verse', cost: 50, desc: 'Fortress hymn — allies within 3 tiles gain +300 armor for 2 turns' },
  furyverse: { id: 'furyverse', name: 'Fury Verse', cost: 45, desc: 'Kiai overflow — your next attack gains +1% damage per point of Will above 100' },
  tracerverse: { id: 'tracerverse', name: 'Tracer Verse', cost: 45, desc: 'Beacon net — attacks by allies within 3 tiles also paint the target until the end of the enemy phase' },
  sirenverse: { id: 'sirenverse', name: 'Siren Verse', cost: 50, desc: 'Wailing fog — enemies within 3 tiles take -15 hit for 2 turns' },
  clarionverse: { id: 'clarionverse', name: 'Clarion Verse', cost: 45, desc: 'War song — allies within 3 tiles gain +10 hit for 2 turns' },
  levinedge: { id: 'levinedge', name: 'Levin Edge', cost: 50, desc: 'Storm blade — your next attack deals +40% damage vs stunned foes' },
  rampartverse: { id: 'rampartverse', name: 'Rampart Verse', cost: 50, desc: 'Shield anthem — allies within 3 tiles take -20% damage from attacks at range 3+ until end of enemy phase' },
  ravageverse: { id: 'ravageverse', name: 'Ravage Verse', cost: 50, desc: 'Mauling strike — the next hit deals +35% damage and cripples the target frame' },
  ghostverse: { id: 'ghostverse', name: 'Ghost Verse', cost: 45, desc: 'Untraceable shot — the next hit deals +25% damage and cannot be countered' },
  curseverse: { id: 'curseverse', name: 'Curse Verse', cost: 50, desc: 'Withering chant — enemies within 3 tiles take +15% damage until end of enemy phase' },
  vigorverse: { id: 'vigorverse', name: 'Vigor Verse', cost: 45, desc: 'Rally hymn — allies within 3 tiles instantly gain +10 Will' },
  savageedge: { id: 'savageedge', name: 'Savage Edge', cost: 45, desc: 'Brutal strike — the next hit deals +20% damage and suppresses the target (-20 hit)' },
  phantomverse: { id: 'phantomverse', name: 'Phantom Verse', cost: 50, desc: 'Ghost protocol — attacks by allies within 3 tiles cannot be countered until end of enemy phase' },
  crimsonverse: { id: 'crimsonverse', name: 'Crimson Verse', cost: 50, desc: 'Blood pact — allies within 3 tiles recover 15% hull on each kill until end of enemy phase' },
  scopeverse: { id: 'scopeverse', name: 'Scope Verse', cost: 45, desc: 'Targeting hymn — allies within 3 tiles +15 hit vs marked or exposed targets until end of enemy phase' },
  doomverse: { id: 'doomverse', name: 'Doom Verse', cost: 50, desc: 'Entropy chant — enemies within 3 tiles decay 8% hull per turn for 2 turns' },
  flowverse: { id: 'flowverse', name: 'Flow Verse', cost: 45, desc: 'Surge hymn — allies within 3 tiles instantly recover +20 EN' },
  truthedge: { id: 'truthedge', name: 'Truth Edge', cost: 50, desc: 'Decisive strike — the next hit cannot graze; near-misses become full hits at +20% damage' },
  oathverse: { id: 'oathverse', name: 'Oath Verse', cost: 55, desc: 'Shared vow — allies within 3 tiles gain +600 armor until end of enemy phase' },
  goreverse: { id: 'goreverse', name: 'Gore Verse', cost: 45, desc: 'Berserk aura — allies within 3 tiles deal +12% damage while hull is below 50%, until end of enemy phase' },
  mirageverse: { id: 'mirageverse', name: 'Mirage Verse', cost: 45, desc: 'Mirage field — allies within 3 tiles gain +15 evade until end of enemy phase' },
  hexverse: { id: 'hexverse', name: 'Hex Verse', cost: 50, desc: 'Hex web — enemies within 3 tiles are marked and suppressed' },
  triumphverse: { id: 'triumphverse', name: 'Triumph Verse', cost: 50, desc: 'Victory chant — allies within 3 tiles deal +10% damage until end of enemy phase' },
  novaedge: { id: 'novaedge', name: 'Nova Edge', cost: 50, desc: 'Supernova strike — the next hit deals +25% damage and surges +10 Will' },
  fortressverse: { id: 'fortressverse', name: 'Fortress Verse', cost: 50, desc: 'Bastion aura — allies within 3 tiles take -20% damage from melee attacks until end of enemy phase' },
  culledge: { id: 'culledge', name: 'Cull Edge', cost: 45, desc: 'Executioner strike — the next hit deals +30% damage vs targets below 40% hull' },
  rendedge: { id: 'rendedge', name: 'Rend Edge', cost: 45, desc: 'Rend plate — the next hit deals +20% damage and permanently compromises the target\'s armor (+10% damage taken)' },
  siphonverse: { id: 'siphonverse', name: 'Siphon Verse', cost: 50, desc: 'Leech uplink — hits landed by allies within 3 tiles drain 10 EN until end of enemy phase' },
  bindverse: { id: 'bindverse', name: 'Bind Verse', cost: 50, desc: 'Snare web — enemies within 3 tiles are slowed and marked' },
  blightverse: { id: 'blightverse', name: 'Blight Verse', cost: 50, desc: 'Corrosion wave — enemies within 3 tiles burn and suffer cracked armor' },
  terrorverse: { id: 'terrorverse', name: 'Terror Verse', cost: 50, desc: 'Dread wave — enemies within 3 tiles are stunned and marked' },
  salvoverse: { id: 'salvoverse', name: 'Salvo Verse', cost: 50, desc: 'Fire-support hymn — allies within 3 tiles deal +15% damage with ranged weapons until end of enemy phase' },
  snaredge: { id: 'snaredge', name: 'Snare Edge', cost: 45, desc: 'Entangling strike — the next hit deals +15% damage and lands suppress + slow' },
  shelterverse: { id: 'shelterverse', name: 'Shelter Verse', cost: 50, desc: 'Warding hymn — allies within 3 tiles take 25% less damage from MAP/area weapons until end of enemy phase' },
  overedge: { id: 'overedge', name: 'Overedge', cost: 45, desc: 'Overdrive strike — next hit deals +40% damage but recoils 10% of own max hull' },
  cleanseverse: { id: 'cleanseverse', name: 'Cleanse Verse', cost: 50, desc: 'Purifying hymn — allies within 3 tiles are cleansed of all status effects, marks, exposure and decay' },
  mireverse: { id: 'mireverse', name: 'Mire Verse', cost: 50, desc: 'Entropy chant — enemies within 3 tiles are slowed and suppressed at once' },
  choirverse: { id: 'choirverse', name: 'Choir Verse', cost: 50, desc: 'Resonant hymn — allies within 3 tiles instantly recover +10 SP' },
  arcedge: { id: 'arcedge', name: 'Arc Edge', cost: 45, desc: 'Chain-lightning strike — next hit deals +10% damage and arcs 30% of it to every enemy adjacent to the target' },
  juggernautverse: { id: 'juggernautverse', name: 'Juggernaut Verse', cost: 50, desc: 'Siege hymn — allies within 3 tiles deal +15% damage with melee weapons until end of enemy phase' },
  splatteredge: { id: 'splatteredge', name: 'Splatter Edge', cost: 45, desc: 'Overkill eruption — if the next hit kills, excess damage erupts onto every enemy adjacent to the kill' },
  voidverse: { id: 'voidverse', name: 'Void Verse', cost: 50, desc: 'Dispel wave — enemies within 3 tiles lose every phase buff and buffing aura' },
  swiftverse: { id: 'swiftverse', name: 'Swift Verse', cost: 45, desc: 'Tailwind hymn — allies within 3 tiles gain +1 movement until end of enemy phase' },
  shroudverse: { id: 'shroudverse', name: 'Shroud Verse', cost: 50, desc: 'Obscuring hex — enemies within 3 tiles lose 15 evade until end of enemy phase' },
  wardverse: { id: 'wardverse', name: 'Ward Verse', cost: 50, desc: 'Aegis hymn — allies within 3 tiles shrug off all incoming status until end of enemy phase' },
  mendverse: { id: 'mendverse', name: 'Mend Verse', cost: 50, desc: 'Repair hymn — allies within 3 tiles regenerate 5% hull per turn for 2 turns' },
  maimedge: { id: 'maimedge', name: 'Maim Edge', cost: 45, desc: 'Maiming strike — next hit +15% damage and permanently wounds the target (-15% hit & damage)' },
  repulseverse: { id: 'repulseverse', name: 'Repulse Verse', cost: 50, desc: 'Counterfield hymn — allies within 3 tiles counter-attack at +1 range until end of enemy phase' },
  silenceverse: { id: 'silenceverse', name: 'Silence Verse', cost: 50, desc: 'Muting wave — enemies within 3 tiles cannot counter-attack until end of enemy phase' },
  magnumverse: { id: 'magnumverse', name: 'Magnum Verse', cost: 45, desc: 'Resupply hymn — allies within 3 tiles instantly recover 1 ammo on every ammo weapon' },
  breaedge: { id: 'breaedge', name: 'Breach Edge', cost: 45, desc: 'Hull-cracking strike — next hit +15% damage and permanently sunders the target (-15 evade, -300 armor)' },
  palisadeverse: { id: 'palisadeverse', name: 'Palisade Verse', cost: 50, desc: 'Bulwark hymn — allies within 3 tiles take 10% less damage until end of enemy phase' },
  hollowedge: { id: 'hollowedge', name: 'Hollow Edge', cost: 45, desc: 'Spirit-breaking strike — next hit +10% damage and drains 20 Will from the target' },
  fearverse: { id: 'fearverse', name: 'Fear Verse', cost: 50, desc: 'Cowardice wave — enemies within 3 tiles deal 10% less damage until end of enemy phase' },
  veilbreakverse: { id: 'veilbreakverse', name: 'Veilbreak Verse', cost: 50, desc: 'Revealing mist — enemies within 3 tiles suffer -15 evade for 2 turns' },
  requiemverse: { id: 'requiemverse', name: 'Requiem Verse', cost: 50, desc: 'Dirge of the fallen — allies within 3 tiles gain +2% damage per destroyed ally until end of enemy phase' },
  cinderedge: { id: 'cinderedge', name: 'Cinder Edge', cost: 45, desc: 'Incendiary strike — next hit +15% damage and ignites the target' },
  steadfastverse: { id: 'steadfastverse', name: 'Steadfast Verse', cost: 50, desc: 'Ironclad hymn — allies within 3 tiles cannot be critically hit until end of enemy phase' },
  maraudedge: { id: 'maraudedge', name: 'Maraud Edge', cost: 45, desc: 'Siphon strike — next hit +15% damage and drains 15 EN from the target' },
  nullverse: { id: 'nullverse', name: 'Null Verse', cost: 50, desc: 'Static blanket — enemies within 3 tiles cannot land critical hits until end of enemy phase' },
  tetherverse: { id: 'tetherverse', name: 'Tether Verse', cost: 50, desc: 'Grav-choke — enemies within 3 tiles suffer -1 movement until end of enemy phase' },
  seraphverse: { id: 'seraphverse', name: 'Seraph Verse', cost: 50, desc: 'Radiant hymn — allies within 3 tiles gain +1 range on non-melee weapons until end of enemy phase' },
  howledge: { id: 'howledge', name: 'Howl Edge', cost: 45, desc: 'Hunting cry — next hit +15% damage and exposes the target' },
  wallverse: { id: 'wallverse', name: 'Wall Verse', cost: 50, desc: 'Rampart hymn — allies within 3 tiles gain a 500-point i-field until end of enemy phase' },
  vampedge: { id: 'vampedge', name: 'Vamp Edge', cost: 45, desc: 'Bloodthirst strike — next hit +10% damage and heals self 25% of damage dealt' },
  rustverse: { id: 'rustverse', name: 'Rust Verse', cost: 50, desc: 'Oxidation wave — enemies within 3 tiles lose 300 armor for 2 turns' },
  stifleverse: { id: 'stifleverse', name: 'Stifle Verse', cost: 50, desc: 'Reactor choke — enemies within 3 tiles regain no EN for 2 turns' },
  scorchverse: { id: 'scorchverse', name: 'Scorch Verse', cost: 55, desc: 'Incendiary hymn — hits landed by allies within 3 tiles also ignite the target until end of enemy phase' },
  disarmedge: { id: 'disarmedge', name: 'Disarm Edge', cost: 45, desc: 'Sabotage strike — next hit +10% damage and strips 2 ammo from every enemy weapon' },
  undyingverse: { id: 'undyingverse', name: 'Undying Verse', cost: 55, desc: 'Guardian hymn — allies within 3 tiles survive a killing blow at 1 HP (once each) until end of enemy phase' },
  twinedge: { id: 'twinedge', name: 'Twin Edge', cost: 50, desc: 'Split arc — the next attack fires one extra strike' },
  jamverse: { id: 'jamverse', name: 'Jam Verse', cost: 50, desc: 'Sabotage wave — enemies within 3 tiles lose 2 ammo from every ammo weapon' },
  despairverse: { id: 'despairverse', name: 'Despair Verse', cost: 50, desc: 'Despair chant — enemies within 3 tiles lose 15 will instantly' },
  lanceverse: { id: 'lanceverse', name: 'Lance Verse', cost: 50, desc: 'Piercing hymn — allies within 3 tiles ignore 20% of target armor until end of enemy phase' },
  pierceedge: { id: 'pierceedge', name: 'Pierce Edge', cost: 45, desc: 'Lance strike — next attack +10% damage and ignores i-fields/barriers entirely' },
  wardenverse: { id: 'wardenverse', name: 'Warden Verse', cost: 50, desc: 'Bulwark hymn — allies within 3 tiles take no terrain damage until end of enemy phase' },
  phantomedge: { id: 'phantomedge', name: 'Phantom Edge', cost: 50, desc: 'Phantom strike — if next attack destroys the target, this frame may act again' },
  rotverse: { id: 'rotverse', name: 'Rot Verse', cost: 50, desc: 'Necrosis wave — enemies within 3 tiles cannot regenerate hull for 2 turns' },
  frailverse: { id: 'frailverse', name: 'Frail Verse', cost: 50, desc: 'Brittleness wave — enemies within 3 tiles take +15% damage for 2 turns' },
  surgeverse: { id: 'surgeverse', name: 'Surge Verse', cost: 50, desc: 'Kiai hymn — allies within 3 tiles gain +15% critical chance until end of enemy phase' },
  muteedge: { id: 'muteedge', name: 'Mute Edge', cost: 45, desc: 'Silencing strike — the next hit deals +10% damage and seals the target’s counter-attack' },
  damperverse: { id: 'damperverse', name: 'Damper Verse', cost: 55, desc: 'Bulwark ward — hits on allies within 3 tiles are capped at 3000 damage until end of enemy phase' },
  dragedge: { id: 'dragedge', name: 'Drag Edge', cost: 45, desc: 'Harpoon strike — the next hit deals +10% damage and hauls the target one tile toward this frame' },
  gloomverse: { id: 'gloomverse', name: 'Gloom Verse', cost: 50, desc: 'Gloom shroud — enemies within 3 tiles suffer -20 hit for 2 turns' },
  tangleverse: { id: 'tangleverse', name: 'Tangle Verse', cost: 50, desc: 'Tangle field — enemies within 3 tiles lose 1 weapon range until end of enemy phase' },
  leechverse: { id: 'leechverse', name: 'Leech Verse', cost: 50, desc: 'Bloodletting hymn — allies within 3 tiles heal 10% of damage dealt until end of enemy phase' },
  blinkedge: { id: 'blinkedge', name: 'Blink Edge', cost: 45, desc: 'Phase strike — next hit +10% damage and teleports this frame beside the target' },
  thornverse: { id: 'thornverse', name: 'Thorn Verse', cost: 50, desc: 'Briar ward — allies within 3 tiles reflect 10% of hit damage back at attackers until end of enemy phase' },
  curseedge: { id: 'curseedge', name: 'Curse Edge', cost: 45, desc: 'Hex strike — next hit +10% damage and curses the target (+15% damage taken until end of enemy phase)' },
  surtaxverse: { id: 'surtaxverse', name: 'Surtax Verse', cost: 50, desc: 'Reactor levy — enemies within 3 tiles pay +10 EN per weapon until end of enemy phase' },
  huskverse: { id: 'huskverse', name: 'Husk Verse', cost: 50, desc: 'Kiai severance — enemies within 3 tiles cannot gain will until end of enemy phase' },
  vaultverse: { id: 'vaultverse', name: 'Vault Verse', cost: 50, desc: 'Prospector hymn — allies within 3 tiles earn +50% salvage per kill until end of enemy phase' },
  shroudedge: { id: 'shroudedge', name: 'Shroud Edge', cost: 45, desc: 'Mirage strike — next hit +10% damage and shrouds the target (-15 evade until end of enemy phase)' },
  freeflowverse: { id: 'freeflowverse', name: 'Freeflow Verse', cost: 50, desc: 'Open conduits — allies within 3 tiles pay 8 less EN per weapon until end of enemy phase' },
  rustedge: { id: 'rustedge', name: 'Rust Edge', cost: 45, desc: 'Corrosion strike — next hit +10% damage and rusts the target (-300 armor for 2 turns)' },
  feebleverse: { id: 'feebleverse', name: 'Feeble Verse', cost: 50, desc: 'Enervation chant — enemies within 3 tiles counter-attack at -25% damage until end of enemy phase' },
  festerverse: { id: 'festerverse', name: 'Fester Verse', cost: 50, desc: 'Blight seal — enemies within 3 tiles cannot be healed until end of enemy phase' },
  slayverse: { id: 'slayverse', name: 'Slay Verse', cost: 50, desc: 'Execution hymn — critical hits by allies within 3 tiles deal +35% damage until end of enemy phase' },
  blindedge: { id: 'blindedge', name: 'Blind Edge', cost: 45, desc: 'Nullifying strike — your next hit deals +10% damage and blinds the target so it cannot land critical hits until end of enemy phase' },
  gloomedge: { id: 'gloomedge', name: 'Gloom Edge', cost: 45, desc: 'Haze strike — next hit +10% damage and shrouds the target in gloom (-20 hit, 2 turns)' },
  sustainverse: { id: 'sustainverse', name: 'Sustain Verse', cost: 50, desc: 'Resupply hymn — allies within 3 tiles fabricate +1 ammo each turn until end of enemy phase' },
  matadoredge: { id: 'matadoredge', name: 'Matador Edge', cost: 45, desc: 'Taunt strike — next hit +10% damage and provokes the target onto this frame' },
  rootverse: { id: 'rootverse', name: 'Root Verse', cost: 55, desc: 'Grave hymn — enemies within 3 tiles are rooted (cannot move) until end of enemy phase' },
  maimverse: { id: 'maimverse', name: 'Maim Verse', cost: 55, desc: 'Massacre chant — enemies within 3 tiles are crippled (-15% hit/damage, -2 move, permanent)' },
  revelverse: { id: 'revelverse', name: 'Revel Verse', cost: 50, desc: 'Festival hymn — allies within 3 tiles gain +3 SP each turn until end of enemy phase' },
  sieveedge: { id: 'sieveedge', name: 'Sieve Edge', cost: 45, desc: 'Shatter strike — next hit +10% damage and collapses the target barrier until end of enemy phase' },
  bulwarkverse: { id: 'bulwarkverse', name: 'Bulwark Verse', cost: 50, desc: 'Rampart hymn — allies within 3 tiles take 20% less damage from melee attackers until end of enemy phase' },
  stifleedge: { id: 'stifleedge', name: 'Stifle Edge', cost: 45, desc: 'Reactor spike — next hit +10% damage and chokes the target reactor (no EN regen for 2 turns)' },
  poxverse: { id: 'poxverse', name: 'Pox Verse', cost: 50, desc: 'Necrosis chant — enemies within 3 tiles corrode for 5% max hull each turn for 2 turns' },
  shatterverse: { id: 'shatterverse', name: 'Shatter Verse', cost: 55, desc: 'Null-field wave — barriers of enemies within 3 tiles collapse until end of enemy phase' },
  anchorverse: { id: 'anchorverse', name: 'Anchor Verse', cost: 50, desc: 'Grav-anchor hymn — allies within 3 tiles cannot be knocked back or dragged until end of enemy phase' },
  poxedge: { id: 'poxedge', name: 'Pox Edge', cost: 45, desc: 'Corrosion strike — next hit +10% damage and corrodes the target for 5% max hull each turn for 2 turns' },
  beamverse: { id: 'beamverse', name: 'Beam Verse', cost: 50, desc: 'Coherent hymn — beam weapons of allies within 3 tiles deal +15% damage until end of enemy phase' },
  frailedge: { id: 'frailedge', name: 'Frail Edge', cost: 45, desc: 'Brittle strike — next hit +10% damage and renders the target brittle (+15% damage taken) for 2 turns' },
  riftverse: { id: 'riftverse', name: 'Rift Verse', cost: 55, desc: 'Grav-rupture chant — enemies within 3 tiles are dragged 1 tile toward this frame' },
  glitchverse: { id: 'glitchverse', name: 'Glitch Verse', cost: 55, desc: 'Static hymn — hits landed by enemies within 3 tiles degrade to grazes (45% damage, no crit or on-hit effects) until end of enemy phase' },
  warlordverse: { id: 'warlordverse', name: 'Warlord Verse', cost: 50, desc: 'Vanguard hymn — melee weapons of allies within 3 tiles deal +15% damage until end of enemy phase' },
  rootedge: { id: 'rootedge', name: 'Grave Edge', cost: 45, desc: 'Grave strike — next hit deals +10% damage and roots the target (no movement) until end of enemy phase' },
  shellverse: { id: 'shellverse', name: 'Shell Verse', cost: 50, desc: 'Barrage hymn — missile weapons of allies within 3 tiles deal +15% damage until end of enemy phase' },
  tangleedge: { id: 'tangleedge', name: 'Tangle Edge', cost: 45, desc: 'Snare strike — next hit deals +10% damage and clips the target’s weapon range by 1 until end of enemy phase' },
  sealverse: { id: 'sealverse', name: 'Seal Verse', cost: 55, desc: 'Lockdown chant — enemies within 3 tiles cannot fire MAP weapons until end of enemy phase' },
  zeroverse: { id: 'zeroverse', name: 'Zero Verse', cost: 50, desc: 'Null-field chant — enemies within 3 tiles lose all weapon-kind resists until end of enemy phase' },
  gunverse: { id: 'gunverse', name: 'Gun Verse', cost: 50, desc: 'Deadeye hymn — gun weapons of allies within 3 tiles deal +15% damage until end of enemy phase' },
  glitchedge: { id: 'glitchedge', name: 'Glitch Edge', cost: 45, desc: 'Static strike — next hit +10% damage and degrades target hits to grazes until end of enemy phase' },
  funnelverse: { id: 'funnelverse', name: 'Funnel Verse', cost: 50, desc: 'Swarm hymn — funnel weapons of allies within 3 tiles deal +15% damage until end of enemy phase' },
  sealedge: { id: 'sealedge', name: 'Seal Edge', cost: 45, desc: 'Lockdown strike — next hit +10% damage and seals target MAP weapons until end of enemy phase' },
  baneverse: { id: 'baneverse', name: 'Bane Verse', cost: 50, desc: 'Hexed chant — hits on enemies within 3 tiles gain +25 critical chance until end of enemy phase' },
  duskverse: { id: 'duskverse', name: 'Dusk Verse', cost: 55, desc: 'Nightfall chant — enemies within 3 tiles are gloomed (-20 hit, 2 turns) and cannot fire MAP weapons until end of enemy phase' },
  reactorverse: { id: 'reactorverse', name: 'Reactor Verse', cost: 50, desc: 'Conduit hymn — allies within 3 tiles restore +30 EN instantly' },
  shrededge: { id: 'shrededge', name: 'Shred Edge', cost: 45, desc: 'Rending strike — next hit +10% damage and strips target weapon-kind resists until end of enemy phase' },
  haloverse: { id: 'haloverse', name: 'Halo Verse', cost: 55, desc: 'Sanctum hymn — allies within 3 tiles gain a 400 barrier until end of enemy phase' },
  surtaxedge: { id: 'surtaxedge', name: 'Surtax Edge', cost: 45, desc: 'Reactor-spike strike — next hit +10% damage and levies target +10 EN per weapon until end of enemy phase' },
  viceverse: { id: 'viceverse', name: 'Vice Verse', cost: 55, desc: 'Crushing grip — enemies within 3 tiles are silenced (no counter) and tethered (-1 move) until end of enemy phase' },
  drainverse: { id: 'drainverse', name: 'Drain Verse', cost: 50, desc: 'Siphon chant — enemies within 3 tiles lose 20 EN instantly' },
  emberverse: { id: 'emberverse', name: 'Ember Verse', cost: 55, desc: 'Pyre hymn — allies within 3 tiles apply BURN on every hit until end of enemy phase' },
  fearedge: { id: 'fearedge', name: 'Fear Edge', cost: 45, desc: 'Dread strike — next hit deals +10% damage and weakens the target (their attacks deal -10%)' },
  bombardverse: { id: 'bombardverse', name: 'Bombard Verse', cost: 55, desc: 'Fire-mission hymn — allies within 3 tiles deal +20% damage with MAP weapons until end of enemy phase' },
  baneedge: { id: 'baneedge', name: 'Bane Edge', cost: 45, desc: 'Hex strike — next hit deals +10% damage and marks the target (+25 crit chance taken)' },
  cowardverse: { id: 'cowardverse', name: 'Coward Verse', cost: 50, desc: 'Terror chant — enemies within 3 tiles lose 20 will instantly' },
  nadirverse: { id: 'nadirverse', name: 'Nadir Verse', cost: 55, desc: 'Null hymn — enemies within 3 tiles lose weapon-kind resists AND cannot fire MAP weapons until end of enemy phase' },
  hasteverse: { id: 'hasteverse', name: 'Haste Verse', cost: 55, desc: 'Tailwind hymn — allies within 3 tiles gain +1 movement until end of enemy phase' },
  feebleedge: { id: 'feebleedge', name: 'Feeble Edge', cost: 45, desc: 'Riposte spike — next hit deals +10% damage and enfeebles the target (counter attacks -25% damage)' },
  flakverse: { id: 'flakverse', name: 'Flak Verse', cost: 50, desc: 'Point-defense hymn — allies within 3 tiles take 20% less damage from ranged attackers until end of enemy phase' },
  crushedge: { id: 'crushedge', name: 'Crush Edge', cost: 45, desc: 'Breaker strike — your next hit deals +10% damage and breaks the target frame' },
  chokerverse: { id: 'chokerverse', name: 'Choker Verse', cost: 50, desc: 'Strangle chant — enemies within 3 tiles counter-attack at -1 range until end of enemy phase' },
  lureverse: { id: 'lureverse', name: 'Lure Verse', cost: 50, desc: 'Bait beacon — enemies within 3 tiles are provoked onto this frame' },
  fableverse: { id: 'fableverse', name: 'Fable Verse', cost: 50, desc: 'Saga hymn — allies within 3 tiles earn +50% EXP until end of enemy phase' },
  ruinverse: { id: 'ruinverse', name: 'Ruin Verse', cost: 50, desc: 'Entropy wave — enemies within 3 tiles suffer armor break and decay 8% hull per turn for 2 turns' },
  anthemverse: { id: 'anthemverse', name: 'Anthem Verse', cost: 55, desc: 'Restoration hymn — allies within 3 tiles instantly recover 15% hull' },
  doomedge: { id: 'doomedge', name: 'Doom Edge', cost: 45, desc: 'Entropy strike — next hit deals +10% damage and dooms the target to decay 8% hull per turn for 3 turns' },
  flareedge: { id: 'flareedge', name: 'Flare Edge', cost: 45, desc: 'Flare strike — next hit deals +10% damage and paints the target plus every enemy adjacent to it' },
  defianceverse: { id: 'defianceverse', name: 'Defiance Verse', cost: 50, desc: 'Defiant hymn — allies within 3 tiles take 20% less damage from higher-level attackers until end of enemy phase' },
  havocverse: { id: 'havocverse', name: 'Havoc Verse', cost: 50, desc: 'Violent chorus — allies within 3 tiles gain +15% critical chance until end of enemy phase' },
  vigilverse: { id: 'vigilverse', name: 'Vigil Verse', cost: 50, desc: 'Watchful hymn — allies within 3 tiles counter at +15% damage until end of enemy phase' },
  mortaledge: { id: 'mortaledge', name: 'Mortal Edge', cost: 50, desc: 'Execution focus — the next attack that lands is a guaranteed critical' },
  sentinelverse: { id: 'sentinelverse', name: 'Sentinel Verse', cost: 50, desc: 'Guardian hymn — allies within 3 tiles intercept attacks aimed at their adjacent allies until end of enemy phase' },
};

// ---------- Pilot traits (passives, resolved in the combat engine) ----------

export const TRAITS: Record<TraitId, { name: string; desc: string }> = {
  ace_instinct: { name: 'Ace Instinct', desc: '+12% damage when Will is 130 or higher' },
  deadeye: { name: 'Deadeye', desc: '+8% hit chance on all attacks' },
  siege_breaker: { name: 'Siege Breaker', desc: '+15% damage against bosses and elite units' },
  field_medic: { name: 'Field Medic', desc: 'REPAIR restores +50% more HP' },
  crimson_fury: { name: 'Crimson Fury', desc: '+10% damage and +8% hit while under 50% HP' },
  falcon_wing: { name: 'Falcon Wing', desc: '+10% hit chance against air units' },
  sovereign: { name: 'Sovereign', desc: '+8% damage at all times' },
  rally: { name: 'Rally', desc: 'allies within 2 tiles gain +8% hit chance' },
};

// ---------- Weapons ----------

const W = (w: WeaponDef) => w;

export const WEAPONS = {
  beamSaber: W({ id: 'beam_saber', name: 'Beam Saber', kind: 'melee', power: 2300, rangeMin: 1, rangeMax: 1, enCost: 5, ammo: null, hitMod: 15, critMod: 15, postMove: true, animSeed: 1 }),
  photonRifle: W({ id: 'photon_rifle', name: 'Photon Rifle', kind: 'beam', power: 1800, rangeMin: 1, rangeMax: 5, enCost: 10, ammo: null, hitMod: 5, postMove: true, animSeed: 2 }),
  missilePods: W({ id: 'missile_pods', name: 'Missile Pods', kind: 'missile', power: 1500, rangeMin: 2, rangeMax: 6, enCost: 0, ammo: 8, hitMod: -5, postMove: true, animSeed: 3, antiAir: true }),
  gatling: W({ id: 'gatling', name: 'Arm Gatling', kind: 'gun', power: 1200, rangeMin: 1, rangeMax: 3, enCost: 0, ammo: 20, hitMod: 10, postMove: true, animSeed: 4, antiAir: true }),
  burstRepeater: W({ id: 'burst_repeater', name: 'Burst Repeater', kind: 'gun', power: 950, rangeMin: 1, rangeMax: 3, enCost: 0, ammo: 30, hitMod: 5, postMove: true, animSeed: 4, antiAir: true, multiHit: 2 }),
  arcCascade: W({ id: 'arc_cascade', name: 'Arc Cascade', kind: 'funnel', power: 2400, rangeMin: 2, rangeMax: 5, enCost: 30, ammo: null, hitMod: 5, postMove: false, animSeed: 13, willReq: 110, chain: 2 }),
  stormArc: W({ id: 'storm_arc', name: 'Storm Arc', kind: 'funnel', power: 2200, rangeMin: 2, rangeMax: 5, enCost: 20, ammo: null, hitMod: 0, postMove: false, animSeed: 29, chain: 2 }),
  plasmaEdge: W({ id: 'plasma_edge', name: 'Plasma Edge', kind: 'melee', power: 2900, rangeMin: 1, rangeMax: 2, enCost: 15, ammo: null, hitMod: 10, critMod: 12, postMove: true, animSeed: 5 }),
  megaBeam: W({ id: 'mega_beam', name: 'Mega Beam Launcher', kind: 'beam', power: 3400, rangeMin: 3, rangeMax: 7, enCost: 40, ammo: null, hitMod: -15, postMove: false, animSeed: 6, willReq: 115 }),
  vulcan: W({ id: 'vulcan', name: 'Head Vulcan', kind: 'gun', power: 800, rangeMin: 1, rangeMax: 2, enCost: 0, ammo: 30, hitMod: 25, postMove: true, animSeed: 7, antiAir: true }),
  railgun: W({ id: 'railgun', name: 'Linear Railgun', kind: 'gun', power: 2600, rangeMin: 2, rangeMax: 6, enCost: 20, ammo: 10, hitMod: 0, postMove: true, animSeed: 8, pierce: true, antiAir: true, sniper: true }),
  heatRod: W({ id: 'heat_rod', name: 'Heat Rod', kind: 'melee', power: 2100, rangeMin: 1, rangeMax: 2, enCost: 8, ammo: null, hitMod: 10, critMod: 10, postMove: true, animSeed: 9, status: 'burn' }),
  stasisRay: W({ id: 'stasis_ray', name: 'Stasis Ray', kind: 'beam', power: 1600, rangeMin: 2, rangeMax: 5, enCost: 12, ammo: null, hitMod: 12, postMove: true, animSeed: 23, status: 'stun' }),
  siegeRain: W({ id: 'siege_rain', name: 'Siege Rain', kind: 'missile', power: 2600, rangeMin: 4, rangeMax: 8, enCost: 18, ammo: null, hitMod: -10, postMove: false, animSeed: 3, antiAir: true, status: 'slow' }),
  chestBlaster: W({ id: 'chest_blaster', name: 'Chest Blaster', kind: 'beam', power: 3100, rangeMin: 1, rangeMax: 4, enCost: 30, ammo: null, hitMod: -5, postMove: false, animSeed: 10, willReq: 115 }),
  mapBuster: W({ id: 'map_buster', name: 'MAP: Buster Mortar', kind: 'missile', power: 2200, rangeMin: 2, rangeMax: 5, enCost: 0, ammo: 3, hitMod: -10, postMove: false, animSeed: 14, willReq: 110, mapRange: 1 }),
  punch: W({ id: 'punch', name: 'Rocket Punch', kind: 'melee', power: 1900, rangeMin: 1, rangeMax: 3, enCost: 10, ammo: null, hitMod: 10, postMove: true, animSeed: 11 }),
  drillLancer: W({ id: 'drill_lancer', name: 'Drill Lancer', kind: 'melee', power: 2700, rangeMin: 1, rangeMax: 1, enCost: 12, ammo: null, hitMod: 5, critMod: 15, postMove: true, animSeed: 12, pierce: true }),
  vampEdge: W({ id: 'vamp_edge', name: 'Vampiric Edge', kind: 'melee', power: 2350, rangeMin: 1, rangeMax: 2, enCost: 14, ammo: null, hitMod: 8, critMod: 12, postMove: true, animSeed: 24, drain: true }),
  soulReaver: W({ id: 'soul_reaver', name: 'Soul Reaver', kind: 'melee', power: 3000, rangeMin: 1, rangeMax: 2, enCost: 18, ammo: null, hitMod: 5, postMove: true, animSeed: 24, drain: true, willDrain: true }),
  funnelArray: W({ id: 'funnel_array', name: 'Funnel Array', kind: 'funnel', power: 2800, rangeMin: 2, rangeMax: 6, enCost: 25, ammo: null, hitMod: 10, postMove: false, animSeed: 13, willReq: 115 }),
  // combination attacks — need the partner unit standing adjacent & unacted
  twinBreaker: W({ id: 'twin_breaker', name: 'Twin Breaker', kind: 'melee', power: 4300, rangeMin: 1, rangeMax: 2, enCost: 25, ammo: null, hitMod: 30, critMod: 20, postMove: true, animSeed: 15, willReq: 110, comboPartner: 'gruntborg' }),
  twinBarrage: W({ id: 'twin_barrage', name: 'Twin Barrage', kind: 'beam', power: 4500, rangeMin: 2, rangeMax: 6, enCost: 30, ammo: null, hitMod: 25, postMove: false, animSeed: 16, willReq: 115, comboPartner: 'zephyra' }),
  crimsonDuet: W({ id: 'crimson_duet', name: 'Crimson Duet', kind: 'melee', power: 4600, rangeMin: 1, rangeMax: 3, enCost: 30, ammo: null, hitMod: 28, critMod: 20, postMove: true, animSeed: 17, willReq: 110, comboPartner: 'vexiaX' }),
  // the two X-Face leads firing in perfect sync — the showpiece combination
  starfallStrike: W({ id: 'starfall_strike', name: 'Starfall Strike', kind: 'beam', power: 4800, rangeMin: 2, rangeMax: 5, enCost: 35, ammo: null, hitMod: 30, critMod: 15, postMove: false, animSeed: 26, willReq: 115, comboPartner: 'valstray' }),
  ironChord: W({ id: 'iron_chord', name: 'Iron Chord', kind: 'melee', power: 4400, rangeMin: 1, rangeMax: 3, enCost: 28, ammo: null, hitMod: 26, critMod: 18, postMove: true, animSeed: 18, willReq: 110, comboPartner: 'raxdenR' }),
  mirageWaltz: W({ id: 'mirage_waltz', name: 'Mirage Waltz', kind: 'funnel', power: 4700, rangeMin: 2, rangeMax: 6, enCost: 32, ammo: null, hitMod: 24, postMove: false, animSeed: 27, willReq: 115, comboPartner: 'vexiaX' }),
  dawnCutter: W({ id: 'dawn_cutter', name: 'Dawn Cutter', kind: 'beam', power: 4600, rangeMin: 1, rangeMax: 4, enCost: 30, ammo: null, hitMod: 25, postMove: true, animSeed: 33, willReq: 115, comboPartner: 'vexiaX' }),
  // v1.8 hero weapons — one extra trick per mech
  arcCannon: W({ id: 'arc_cannon', name: 'Arc Cannon', kind: 'beam', power: 3200, rangeMin: 2, rangeMax: 5, enCost: 28, ammo: null, hitMod: 5, postMove: false, animSeed: 17, willReq: 105 }),
  thermoCharge: W({ id: 'thermo_charge', name: 'Thermobaric Charge', kind: 'missile', power: 3600, rangeMin: 1, rangeMax: 3, enCost: 0, ammo: 4, hitMod: 0, postMove: false, animSeed: 18, willReq: 110, knockback: true }),
  railVolley: W({ id: 'rail_volley', name: 'Railgun Volley', kind: 'gun', power: 2000, rangeMin: 1, rangeMax: 4, enCost: 0, ammo: 12, hitMod: 15, postMove: true, animSeed: 19, status: 'break', sniper: true }),
  flareField: W({ id: 'flare_field', name: 'Flare Field', kind: 'funnel', power: 2400, rangeMin: 1, rangeMax: 4, enCost: 20, ammo: null, hitMod: 15, postMove: true, animSeed: 20, status: 'burn' }),
  flareDart: W({ id: 'flare_dart', name: 'Flare Dart', kind: 'beam', power: 1600, rangeMin: 2, rangeMax: 5, enCost: 12, ammo: null, hitMod: 10, postMove: true, animSeed: 21, status: 'mark' }),
  havocMortar: W({ id: 'havoc_mortar', name: 'Havoc Mortar', kind: 'missile', power: 2000, rangeMin: 3, rangeMax: 6, enCost: 16, ammo: null, hitMod: -5, postMove: false, animSeed: 4, status: 'supp' }),
  hexBolt: W({ id: 'hex_bolt', name: 'Hex Bolt', kind: 'beam', power: 2400, rangeMin: 2, rangeMax: 5, enCost: 12, ammo: null, hitMod: -5, postMove: true, animSeed: 22, status: 'break' }),
  nullChord: W({ id: 'null_chord', name: 'Null Chord', kind: 'beam', power: 800, rangeMin: 1, rangeMax: 3, enCost: 8, ammo: null, hitMod: 10, postMove: true, animSeed: 22, status: 'supp' }),
  mapFlare: W({ id: 'map_flare', name: 'MAP: Flare Burst', kind: 'funnel', power: 1900, rangeMin: 2, rangeMax: 5, enCost: 45, ammo: null, hitMod: -5, postMove: false, animSeed: 20, willReq: 105, mapRange: 1 }),
  mapShelling: W({ id: 'map_shelling', name: 'MAP: Siege Howitzer', kind: 'missile', power: 2400, rangeMin: 2, rangeMax: 6, enCost: 40, ammo: null, hitMod: -10, postMove: false, animSeed: 25, mapRange: 1 }),
  mapCataclysm: W({ id: 'map_cataclysm', name: 'MAP: Void Cataclysm', kind: 'funnel', power: 2800, rangeMin: 2, rangeMax: 6, enCost: 60, ammo: null, hitMod: -5, postMove: false, animSeed: 26, mapRange: 2 }),
  // ALL weapon — saturates every hostile inside range in one volley, no counters
  omniBarrage: W({ id: 'omni_barrage', name: 'ALL: Omni Barrage', kind: 'missile', power: 2100, rangeMin: 1, rangeMax: 4, enCost: 0, ammo: 4, hitMod: 0, postMove: false, animSeed: 27, willReq: 110, all: true }),
  fangRipper: W({ id: 'fang_ripper', name: 'Fang Ripper', kind: 'melee', power: 3300, rangeMin: 1, rangeMax: 2, enCost: 30, ammo: null, hitMod: 12, postMove: true, animSeed: 54, breaker: true }),
  pileBunker: W({ id: 'pile_bunker', name: 'Pile Bunker', kind: 'melee', power: 3400, rangeMin: 1, rangeMax: 1, enCost: 16, ammo: 3, hitMod: -10, critMod: 40, postMove: true, animSeed: 24 }),
  siegeCrusher: W({ id: 'siege_crusher', name: 'Siege Crusher', kind: 'melee', power: 3600, rangeMin: 1, rangeMax: 1, enCost: 20, ammo: null, hitMod: -5, postMove: true, animSeed: 55, breaker: true, knockback: true }),
  arkZenith: W({ id: 'ark_zenith', name: 'Ark Zenith Saber', kind: 'melee', power: 5200, rangeMin: 1, rangeMax: 2, enCost: 45, ammo: null, hitMod: 20, critMod: 20, postMove: true, animSeed: 56, aceReq: 5 }),
  novaMortar: W({ id: 'nova_mortar', name: 'MAP: Nova Mortar', kind: 'missile', power: 3100, rangeMin: 2, rangeMax: 5, enCost: 0, ammo: 3, hitMod: -5, postMove: false, animSeed: 57, mapRange: 1, aceReq: 5 }),
  eclipseLance: W({ id: 'eclipse_lance', name: 'Eclipse Lance', kind: 'beam', power: 4900, rangeMin: 3, rangeMax: 8, enCost: 50, ammo: null, hitMod: 10, postMove: false, animSeed: 58, aceReq: 5, sniper: true, pierce: true }),
  wraithBloom: W({ id: 'wraith_bloom', name: 'Wraith Bloom', kind: 'funnel', power: 3800, rangeMin: 2, rangeMax: 6, enCost: 40, ammo: null, hitMod: 15, postMove: true, animSeed: 59, aceReq: 5 }),
  arkBarrageW: W({ id: 'ark_barrage', name: 'MAP: Ark Barrage', kind: 'missile', power: 2400, rangeMin: 2, rangeMax: 8, enCost: 0, ammo: null, hitMod: 0, postMove: true, animSeed: 60, mapRange: 2 }),
  militiaRifle: W({ id: 'militia_rifle', name: 'Defense Rifle', kind: 'gun', power: 1500, rangeMin: 1, rangeMax: 4, enCost: 0, ammo: 12, hitMod: 8, postMove: true, animSeed: 21 }),
  voidLance: W({ id: 'void_lance', name: 'Void Lance', kind: 'beam', power: 3300, rangeMin: 2, rangeMax: 7, enCost: 32, ammo: null, hitMod: 0, critMod: 8, postMove: false, animSeed: 25, willReq: 115, pierce: true, sniper: true }),
};

// ---------- Pilots ----------

const P = (p: PilotDef) => p;

export const PILOTS = {
  ray: P({ name: 'Ray Ardent', callsign: 'X-1', melee: 68, ranged: 74, defense: 60, evade: 72, maxSp: 60, spirits: ['strike', 'valor', 'focus', 'accel', 'zeal', 'roar', 'soul', 'frenzy', 'soulburn', 'pyre', 'skyfall', 'blade', 'judge', 'rampage', 'voidedge', 'tempestedge', 'hellfire', 'sunderstorm', 'quakeedge', 'heavensverse', 'levinedge', 'savageedge', 'truthedge', 'novaedge', 'mortaledge', 'snaredge', 'arcedge', 'doomedge', 'flareedge', 'breaedge', 'cinderedge', 'howledge', 'disarmedge', 'pierceedge', 'muteedge', 'blinkedge', 'curseedge', 'shroudedge', 'blindedge', 'gloomedge', 'sieveedge', 'poxedge', 'rootedge', 'glitchedge', 'shrededge', 'fearedge', 'feebleedge'], faceColor: '#ffb347', trait: 'ace_instinct' }),
  mira: P({ name: 'Mira Solen', callsign: 'X-2', melee: 55, ranged: 80, defense: 55, evade: 78, maxSp: 55, spirits: ['focus', 'strike', 'accel', 'snipe', 'rouse', 'fortune', 'trust', 'emp', 'deadshot', 'scan', 'marksman', 'shatter', 'tracer', 'veil', 'stalker', 'trueshot', 'armorrot', 'lockcascade', 'firelink', 'staticchoir', 'pinverse', 'breachverse', 'exposeverse', 'tracerverse', 'ghostverse', 'scopeverse', 'mirageverse', 'bindverse', 'siphonverse', 'cleanseverse', 'voidverse', 'swiftverse', 'repulseverse', 'fearverse', 'nullverse', 'rustverse', 'jamverse', 'rotverse', 'gloomverse', 'surtaxverse', 'feebleverse', 'chokerverse', 'rootverse', 'poxverse', 'riftverse', 'sealverse', 'baneverse', 'viceverse', 'cowardverse'], faceColor: '#7ee7ff', trait: 'deadeye' }),
  gara: P({ name: 'Gara Dune', callsign: 'Y-1', melee: 78, ranged: 60, defense: 74, evade: 58, maxSp: 50, spirits: ['grit', 'valor', 'guard', 'vigor', 'sunder', 'provoke', 'phalanx', 'breach', 'charity', 'intimidate', 'warsong', 'fluster', 'overrun', 'avenger', 'suppress', 'banner', 'drawfire', 'standfirm', 'ironoath', 'bulwarkaria', 'mirrorwall', 'valiantverse', 'bastionverse', 'rampartverse', 'phantomverse', 'oathverse', 'fortressverse', 'sentinelverse', 'shelterverse', 'juggernautverse', 'defianceverse', 'mendverse', 'palisadeverse', 'steadfastverse', 'wallverse', 'undyingverse', 'wardenverse', 'damperverse', 'thornverse', 'freeflowverse', 'flakverse', 'sustainverse', 'bulwarkverse', 'beamverse', 'shellverse', 'funnelverse', 'haloverse', 'bombardverse'], faceColor: '#ff9d9d', trait: 'siege_breaker' }),
  orin: P({ name: 'Orin Vale', callsign: 'Z-1', melee: 62, ranged: 70, defense: 66, evade: 66, maxSp: 65, spirits: ['guard', 'focus', 'valor', 'flash', 'disrupt', 'bless', 'lucky', 'mercy', 'purge', 'cheer', 'expose', 'decoy', 'hymn', 'sanctuary', 'empower', 'ward', 'relay', 'inspire', 'warhorn', 'safeguard', 'absolution', 'litany', 'aegis', 'sanctumhymn', 'miraclechorus', 'gracehymn', 'renewalverse', 'foresightverse', 'clarionverse', 'vigorverse', 'flowverse', 'triumphverse', 'vigilverse', 'salvoverse', 'choirverse', 'anthemverse', 'wardverse', 'magnumverse', 'requiemverse', 'seraphverse', 'scorchverse', 'lanceverse', 'surgeverse', 'leechverse', 'vaultverse', 'slayverse', 'fableverse', 'revelverse', 'anchorverse', 'warlordverse', 'gunverse', 'reactorverse', 'emberverse', 'hasteverse'], faceColor: '#b6ff9d', trait: 'field_medic' }),
  karg: P({ name: 'Col. Karg Draven', callsign: 'BOSS', melee: 75, ranged: 75, defense: 70, evade: 65, maxSp: 70, spirits: ['valor', 'strike'], faceColor: '#d0a0ff', lastWords: 'Rex is scrap... the Empire builds another. Always.', killQuip: 'Another Aegis relic for the pyre.' }),
  grunt: P({ name: 'Soldier', callsign: 'GR', melee: 56, ranged: 56, defense: 52, evade: 52, maxSp: 30, spirits: [], faceColor: '#bbbbbb' }),
  centurion: P({ name: 'Centurion', callsign: 'CT', melee: 64, ranged: 66, defense: 60, evade: 58, maxSp: 40, spirits: ['grit'], faceColor: '#e0c0ff', trait: 'rally', lastWords: 'The line... holds without me.', killQuip: 'Forward! For the Empire.' }),
  civ: P({ name: 'Convoy Crew', callsign: 'CVY', melee: 40, ranged: 40, defense: 40, evade: 40, maxSp: 0, spirits: [], faceColor: '#c8b090' }),
  militia: P({ name: 'Ark Militia', callsign: 'DEF', melee: 55, ranged: 60, defense: 58, evade: 55, maxSp: 0, spirits: [], faceColor: '#8fb8dd', trait: 'rally' }),
};

// ---------- Units (original mecha, 3 factions X / Y / Z) ----------

const U = (u: UnitDef) => u;

export const UNITS: Record<string, UnitDef> = {
  // --- player squad ---
  valstray: U({ id: 'valstray', name: 'Valstray', title: 'X-Face Vanguard', color: '#2f6fd0', accent: '#9fd0ff', maxHp: 5800, maxEn: 140, armor: 1050, mobility: 118, moveRange: 6, moveType: 'land', weapons: [WEAPONS.arkZenith, WEAPONS.beamSaber, WEAPONS.photonRifle, WEAPONS.missilePods, WEAPONS.twinBreaker, WEAPONS.arcCannon, WEAPONS.dawnCutter], pilot: PILOTS.ray, transformInto: 'valstray_s' }),
  // Valstray's flight frame — lighter armor, much faster, sheds workshop upgrades for raw speed
  valstray_s: U({ id: 'valstray_s', name: 'Valstray Strider', title: 'X-Face Skyframe', color: '#3a8de0', accent: '#bfe4ff', maxHp: 5400, maxEn: 140, armor: 880, mobility: 148, moveRange: 8, moveType: 'air', weapons: [WEAPONS.beamSaber, WEAPONS.photonRifle, WEAPONS.vulcan, WEAPONS.arcCannon, WEAPONS.dawnCutter], pilot: PILOTS.ray }),
  arielis: U({ id: 'arielis', name: 'Arielis', title: 'X-Face Sniper', color: '#38b6c9', accent: '#c8f6ff', maxHp: 4600, maxEn: 160, armor: 900, mobility: 132, moveRange: 7, moveType: 'air', weapons: [WEAPONS.eclipseLance, WEAPONS.megaBeam, WEAPONS.photonRifle, WEAPONS.vulcan, WEAPONS.twinBarrage, WEAPONS.railVolley, WEAPONS.starfallStrike], pilot: PILOTS.mira }),
  gruntborg: U({ id: 'gruntborg', name: 'Grunborg', title: 'Y-Face Heavy', color: '#c94f4f', accent: '#ffd0c0', maxHp: 7200, maxEn: 110, armor: 1400, mobility: 92, moveRange: 5, moveType: 'land', weapons: [WEAPONS.novaMortar, WEAPONS.havocMortar, WEAPONS.drillLancer, WEAPONS.railgun, WEAPONS.gatling, WEAPONS.mapBuster, WEAPONS.thermoCharge, WEAPONS.omniBarrage, WEAPONS.ironChord], pilot: PILOTS.gara }),
  zephyra: U({ id: 'zephyra', name: 'Zephyra', title: 'Z-Face Duelist', color: '#5fbf62', accent: '#d8ffd8', maxHp: 5400, maxEn: 150, armor: 1000, mobility: 126, moveRange: 6, moveType: 'air', weapons: [WEAPONS.wraithBloom, WEAPONS.plasmaEdge, WEAPONS.chestBlaster, WEAPONS.vulcan, WEAPONS.flareField, WEAPONS.flareDart, WEAPONS.mapFlare, WEAPONS.mirageWaltz], pilot: PILOTS.orin, repairer: true, supplier: true, transformInto: 'zephyra_w' }),
  // Zephyra's skirmisher frame — a ghost on the field: faster, harder to pin, paper-thin
  zephyra_w: U({ id: 'zephyra_w', name: 'Zephyra Wisp', title: 'Z-Face Ghost', color: '#8fe08f', accent: '#eaffea', maxHp: 5200, maxEn: 150, armor: 750, mobility: 158, moveRange: 8, moveType: 'air', weapons: [WEAPONS.plasmaEdge, WEAPONS.chestBlaster, WEAPONS.flareField, WEAPONS.flareDart, WEAPONS.mirageWaltz], pilot: PILOTS.orin }),
  // --- enemy ---
  zolda: U({ id: 'zolda', name: 'Zolda', title: 'Imperial Mass Unit', color: '#6b6f7a', accent: '#c9ccd6', maxHp: 3800, maxEn: 100, armor: 850, mobility: 88, moveRange: 5, moveType: 'land', weapons: [WEAPONS.gatling, WEAPONS.heatRod], pilot: PILOTS.grunt }),
  zoldaAir: U({ id: 'zolda_air', name: 'Zolda Flyer', title: 'Imperial Air Unit', color: '#7a6b6f', accent: '#d6c9cc', maxHp: 3400, maxEn: 110, armor: 700, mobility: 104, moveRange: 7, moveType: 'air', weapons: [WEAPONS.missilePods, WEAPONS.vulcan], pilot: PILOTS.grunt }),
  kargan: U({ id: 'kargan', name: 'Kargan Rex', title: 'Imperial Ace', color: '#8a2fbe', accent: '#e0b3ff', maxHp: 8600, maxEn: 170, armor: 1250, mobility: 124, moveRange: 6, moveType: 'air', weapons: [WEAPONS.plasmaEdge, WEAPONS.funnelArray, WEAPONS.chestBlaster], pilot: PILOTS.karg, boss: true, level: 5 }),
  arkmilitia: U({ id: 'arkmilitia', name: 'Ark Militia', title: 'Colony Defender', color: '#3e4a5a', accent: '#8fb8dd', maxHp: 3800, maxEn: 80, armor: 420, mobility: 62, moveRange: 4, moveType: 'land', weapons: [WEAPONS.militiaRifle], pilot: PILOTS.militia }),
};

// ---------- Terrain table ----------

export interface TerrainInfo {
  name: string;
  def: number;
  eva: number;
  moveCost: { land: number; air: number };
  passable: { land: boolean; air: boolean };
  hpRegen?: number; // fraction of maxHp restored at phase start
  enRegen?: number; // extra EN restored at phase start
  hpDmg?: number; // fraction of maxHp lost per phase while standing on it
  color: string;
  glyph: string;
}

export const TERRAIN_INFO: Record<Terrain, TerrainInfo> = {
  plain: { name: 'Plains', def: 0, eva: 0, moveCost: { land: 1, air: 1 }, passable: { land: true, air: true }, color: '#3d5a3d', glyph: '' },
  road: { name: 'Road', def: 0, eva: -5, moveCost: { land: 1, air: 1 }, passable: { land: true, air: true }, color: '#5a5348', glyph: '═' },
  forest: { name: 'Forest', def: 100, eva: 15, moveCost: { land: 2, air: 1 }, passable: { land: true, air: true }, color: '#1f4d2a', glyph: '♣' },
  mountain: { name: 'Mountain', def: 150, eva: 20, moveCost: { land: 3, air: 1 }, passable: { land: true, air: true }, color: '#5c4a3a', glyph: '▲' },
  water: { name: 'Water', def: 0, eva: 0, moveCost: { land: 99, air: 1 }, passable: { land: false, air: true }, color: '#1e3f66', glyph: '≈' },
  city: { name: 'City', def: 200, eva: -10, moveCost: { land: 1, air: 1 }, passable: { land: true, air: true }, hpRegen: 0.08, enRegen: 8, color: '#4a4a58', glyph: '▦' },
  base: { name: 'Base', def: 250, eva: 0, moveCost: { land: 1, air: 1 }, passable: { land: true, air: true }, hpRegen: 0.12, enRegen: 10, color: '#584a6e', glyph: '⌂' },
  void: { name: 'Void', def: 0, eva: 10, moveCost: { land: 1, air: 1 }, passable: { land: true, air: true }, color: '#141428', glyph: '·' },
  moon: { name: 'Moon Surface', def: 50, eva: 5, moveCost: { land: 2, air: 1 }, passable: { land: true, air: true }, color: '#555560', glyph: '◌' },
  desert: { name: 'Desert', def: -50, eva: -10, moveCost: { land: 2, air: 1 }, passable: { land: true, air: true }, color: '#8a7a4a', glyph: '∴' },
  snow: { name: 'Snowfield', def: 30, eva: 5, moveCost: { land: 2, air: 1 }, passable: { land: true, air: true }, color: '#b8c4d0', glyph: '❄' },
  lava: { name: 'Lava Field', def: 0, eva: 0, moveCost: { land: 3, air: 1 }, passable: { land: true, air: true }, hpDmg: 0.08, color: '#8a2a12', glyph: '♨' },
  ruins: { name: 'Ruins', def: 180, eva: 10, moveCost: { land: 2, air: 1 }, passable: { land: true, air: true }, color: '#4a4456', glyph: '▤' },
};

// ---------- Mission SSS: "Steel Sky Siege" ----------

// prettier-ignore
const T: Terrain[][] = [
  // 0        1        2        3        4        5        6        7        8        9        10       11       12       13
  ['mountain','mountain','plain','plain','forest','plain','plain','plain','plain','plain','forest','plain','plain','plain'],   // 0
  ['mountain','plain','plain','forest','forest','plain','road','road','road','plain','plain','plain','plain','water'],      // 1
  ['plain','plain','plain','plain','forest','plain','road','plain','road','plain','plain','city','plain','water'],          // 2
  ['plain','city','road','road','road','road','road','plain','road','road','road','city','plain','water'],                  // 3
  ['plain','plain','plain','plain','forest','plain','road','plain','road','plain','forest','plain','plain','water'],        // 4
  ['water','plain','plain','forest','forest','plain','road','plain','plain','plain','forest','mountain','plain','water'],   // 5
  ['water','water','plain','plain','plain','plain','road','plain','city','plain','plain','mountain','plain','plain'],       // 6
  ['plain','plain','plain','city','plain','forest','road','road','road','road','plain','plain','plain','plain'],            // 7
  ['plain','base','plain','city','plain','forest','plain','plain','plain','road','plain','plain','city','plain'],           // 8
  ['plain','plain','plain','plain','plain','plain','plain','forest','plain','road','road','road','road','plain'],           // 9
];

export const MISSION_SSS: MapDef = {
  id: 'sss',
  name: 'MISSION SSS',
  subtitle: 'Steel Sky Siege',
  cols: 14,
  rows: 10,
  terrain: T,
  objective: 'Defeat all Imperial units. Ace pilot Col. Karg Draven commands the Kargan Rex — bring him down.',
  playerSpawns: [
    { defId: 'valstray', pos: { x: 1, y: 8 } },
    { defId: 'gruntborg', pos: { x: 3, y: 9 } },
    { defId: 'arielis', pos: { x: 4, y: 8 } },
    { defId: 'zephyra', pos: { x: 2, y: 9 } },
  ],
  enemySpawns: [
    { defId: 'zolda', pos: { x: 11, y: 2 } },
    { defId: 'zolda', pos: { x: 12, y: 3 } },
    { defId: 'zoldaAir', pos: { x: 10, y: 1 } },
    { defId: 'zoldaAir', pos: { x: 12, y: 5 } },
    { defId: 'zolda', pos: { x: 11, y: 4 } },
    { defId: 'kargan', pos: { x: 12, y: 1 } }, // far corner + boss hold: not attackable turn 1
  ],
  bossHoldUntil: 3, // Kargan Rex holds position until turn 3
  reinforce: { turn: 4, comp: ['zolda', 'zolda', 'zoldaAir'] },
};
